# Generated by Django 5.0.8 on 2024-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('concept_title', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('academy', models.CharField(max_length=255)),
                ('proof', models.CharField(max_length=255)),
            ],
        ),
    ]
